language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=py34
install:
    - sudo apt-get update
    - sudo apt-get install python3.4
    - pip install tox
script: tox -e $TOX_ENV
notifications:
    email: false
